### ISSUE TITLE
Follow cursor rather than top of the window

### ISSUE THREAD

**Issue by typhooncamel** [wellle/context.vim#10]
Currently, at least in my setup, the context window follows the top of the window, not the cursor. So if you have two short functions, one is at the top and one is in the middle or bottom of the screen, even if you cursor is at the bottom of the screen the context will show the first function at the top of the screen. Is there any way to have it follow the cursor?

**Comment by wellle** [comment]
Personally I don't feel like this would be useful, as in your case you already have the full context just on screen. But I'm willing to implement this as an option and have you try it if you really like it. Not high prio yet though.

**Comment by wellle** [comment]
@typhooncamel @jclifford-zd: I pushed a branch which should do what you asked for: https://github.com/wellle/context.vim/compare/10-cursor-line

Can you please use that for a bit and let me know if that's really what you want? In that case I might add a setting to enable this behavior. Thanks!

**Comment by Pawan-Bishnoi** [comment]
Thanks @wellle for the nice work you have done. I tried the 'follow the cursor' option but it turned out to be confusing and not as useful as I thought it would be.

I have a different suggestion:
> Show the preview window only if a block of code overflows the screen

What do you think @typhooncamel

**Comment by wellle** [comment]
@Pawan-Bishnoi: I'm not sure I understand. Can you clarify what you mean by `a block of code`?

**Comment by Pawan-Bishnoi** [comment]
<img width="1680" alt="vimContext" src="https://user-images.githubusercontent.com/12809727/71545717-6e52e580-29b4-11ea-8c02-4a86cbe4ef79.png">

I mean I would imagine the preview screen to open up when the definition of a function/class (that I am currently looking at) moves out of screen

**Comment by wellle** [comment]
@Pawan-Bishnoi: Thanks! I pushed a new branch which only adds lines to the context (still based on the cursor lines) which are not visible on screen:
https://github.com/wellle/context.vim/compare/10-cursor-line-filtered

I think there are still some issues where the context is not always automatically updated, but could you try that and let me know if that seems useful? Thanks!

**Comment by Pawan-Bishnoi** [comment]
Thanks @wellle
That looks much better. I agree we might be missing a few corner cases here, I will keep an eye out for them.

**Comment by jclifford-zd** [comment]
@wellle thanks for this. I have been using `10-cursor-line` and it seems to work perfectly.

**Comment by wellle** [comment]
Okay, thank you both for the feedback.

I'm currently working on something else (for #4) and will get back to this afterwards.

**Comment by typhooncamel** [comment]
Thank you @wellle and everyone else - sorry, I've been away and couldn't check it out. I agree that `10-cursor-line` is what I was after.

**Comment by idbrii** [comment]
10-cursor-line-filtered is just what I was looking for! I'm used to invoking context with a mapping (I have a command that `:echo`s it -- but context does it better), so I don't want context on the screen unless it's currently relevant and I'd rather see more code at the top of the screen than context for a function I'm not currently editing.

Look forward to this being an option in master (to use it with popupwin)!

**Comment by maxigit** [comment]
This plugin is fantastic and is really handy for example to edit html file. This feature will really help to see which tags are the parent or too check if which if branch your are even when the screen is to small to trigger the context.

**Comment by wellle** [comment]
Thanks for the interest in this everyone! I did some work on this yesterday. I'm basically starting again because there's some big differences after #22 had been merged.

The non filtered version is fairly similar to before (branch `10-cursor-line`).

But the filtered version (branch `10-cursor-line-filtered`) turns out to be more challenging. I'll need some more time to decide if a simple approach will be enough (might be slightly misleading in some cases).

And I still haven't decided if I want to support one of them or both of these variations. To me personally the filtered one seems more visually appealing, but is harder to get right on my end.

So yeah, I'll get back to this eventually. :v:

**Comment by wmusial** [comment]
thanks @wellle , your custom branch `10-cursor-line-filtered` is *exactly* what i was looking for.

I personally feel that the "cursor-line-filtered` is really the primary use case of this plugin. 
Consider what happens when one's editing the line under the cursor, and starts wondering about its context. I personally start scanning vertically upwards, away from the current line, searching for enclosing scopes. When i reach the top of the screen, I can't continue the mental search without scrolling of the buffer. This is when this context plugin comes in: it summarizes what's not visible on the screen but in relation to the currently highlighted line, not just the arbitrary line atop the screen.. That's exactly what the cursor-line-filtered mod accomplishes!

**Comment by wellle** [comment]
@typhooncamel @Pawan-Bishnoi @jclifford-zd @idbrii @maxigit @wmusial @nilsboy @ThomasFeher @igorsol @mredaelli @GaurangTandon

Thanks for the interest and patience everyone. I've finished working on this over the last few days and just opened https://github.com/wellle/context.vim/pull/76. I'd appreciate if some of you could try this new version and give me some feedback on it before I merge the PR. Thank you!

**Comment by wmusial** [comment]
works perfectly 😍 . Thanks @wellle !!!
