### ISSUE TITLE
Artifacts to the left of the context window

### ISSUE THREAD

**Issue by knubie** [wellle/context.vim#24]
First of all, great job on this plugin, love the idea!

I'm seeing some artifacts to the left hand side of the context window.

![Screen Shot 2020-01-27 at 8 38 14 AM](https://user-images.githubusercontent.com/431251/73178971-620b9680-40e0-11ea-9c79-f90325812975.png)

Any idea what could be causing this?

P.S. That screenshot is from the `10-cursor-line-filtered` branch, but I'm seeing the same artifacts on `master` as well.)

**Comment by wellle** [comment]
Hmm. So I'm using the `'signcolumn'` setting to add some padding. Basically to align the context lines with the buffer which has the column on the left to show the line numbers. The grey background is probably because of your colorscheme.

1. Could you tell me what colorscheme you're using? Also which Vim/Neovim version and what terminal application?
2. Could you try the same with a different colorscheme, maybe just `default`? And let me know if that would "fix" the background color?

As for the blue characters within that grey column I have no idea. I wonder if you may have any other plugins which would show such signs?

3. I see your dotfiles repo, but it seems to be possibly outdated. Could you share your current vimrc with all plugins you're using?
4. Maybe you could even try to disable all other plugins temporarily and see if the blue characters disappear then?
5. Could you try reproducing this on a different file? Maybe it's something file type specific? (I doubt it though)
6. And it looks like your running inside of tmux or something similar. Could you try if the issue persists if you open Vim in a new terminal (not within tmux or similar)?

Thanks for reporting!

**Comment by knubie** [comment]
Hey @wellle thanks for the quick reply

1. It's a custom color scheme. I made a gist [here](https://gist.github.com/knubie/12fd5542aaaa1e3497f2ccfbb34ff403). Using neovim version 0.4.3
2. Tried using the default color scheme, but seeing the same artifacts.
3. Here's a gist of my [vimrc](https://gist.github.com/knubie/d4cc3fb2ba010cd522c767c4fe12883d).
4. Tried that as well but still seeing the blue characters.
5. Tried this in a javascript file in another project and still seeing the exact same characters. They seem to be related to indentation length. `-` for tab and `|` for space.
6. Not running inside of tmux or anything like that. The tab bar at the bottom is just part of the terminal emulator I'm using (kitty). I tried running vim in the default MacOS terminal and saw the same artifacts.

I'm using the 16 colors defined in my terminal settings. The foreground color in the artifact is `Blue` aka `12`, but I don't think the background color is defined at all in my terminal colors.

I tried going through and changing all of the highlights in my color scheme that had `ctermfg=Blue`, but none of them affected the color of the characters being shown in the artifact.

**Comment by knubie** [comment]
I don't know if this is related at all, but I'm also seeing some blank lines in the context window:

![Screen Shot 2020-01-27 at 11 40 55 AM](https://user-images.githubusercontent.com/431251/73194396-267dc600-40fa-11ea-87a1-0845b563656c.png)

And here is what the actual code looks like:

```clojure
(defn back-button-section
  "child can either be a card, if previewing a single card, or
  ::schema/review-params, if [:ui :page] is :learn, :review or :rereview.
  
  In either case, we expect a hash with either [:note-id :xx] or [:deck-id xx]"

  [card params & [type]]

  (r/with-let [child  (or card params)
               parent (case type
                        :note (<-- [:notes/find (:parent-id child)])
                        :deck (<-- [:decks/find (:parent-id child)])

                        ;; Default
                        (match child
                          {:note-id id} (<-- [:notes/find id])
                          {:deck-id id} (<-- [:decks/find id])
                          :all          nil
                          :else         nil))

               back   #(case type
                         :note (if (or (.-metaKey %) (.-ctrlKey %))
                                 (--> [:ui/modal:view-note (:parent-id child)])
                                 (--> [:ui/page [:note {:note-id
                                                        (:parent-id child)}]]))
                         :deck (--> [:ui/page [:deck {:deck-id
                                                      (:parent-id child)}]])

                         ;; Default
                         (match child
                          {:note-id id} (if (or (.-metaKey %) (.-ctrlKey %))
                                          (--> [:ui/modal:view-note id])
                                          (--> [:ui/page [:note {:note-id id}]]))
                          {:deck-id id} (--> [:ui/page [:deck {:deck-id id}]])
                          :all          (--> [:ui/page [:home]])
                          :else         :noop))

               _ (bind "escape" #(when-not (<-- [:ui/modal]) (back)))]


    [:<>
     (if (:parent-id parent)
       [:<>
        [back-button-section parent nil
         (or type
             (match child {:note-id _} :note
                          {:deck-id _} :deck
                          :else        :none))]
        [:span {:style {:opacity 0.4
                        :margin "0 10px"}}
         "/"]])
; ...
```

Based on the demo gifs I would imagine it should look something like this?

```
(defn back-button-section
  ...
  (r/with-let [child  (or card params)
    ...
    [:<>
     [back-button-section parent nil ... ]
     ------------------------------------------------
```

**Comment by wellle** [comment]
The blank lines are intended. They are used to make sure there are no lines visible in the buffer without full context. And the plugin shouldn't scroll the buffer as that would probably be disorienting.

In your example the `[:span` line is the first line in the buffer with enough space to show it's context. But its context is only five lines, while there are nine lines above it (hidden by the floating window). One line is used for the border characters, leaves three blank lines.

For example lets look at the line above the `[:span`: If you scroll your buffer down one line you'll see that its context is eight lines heigh. Plus the border line the floating window needs nine lines to display it. But before you scrolled there were only eight lines available above, so it didn't fit.

The same is true for all other lines above the `[:span` line, each of them has a context which is too big display without obstructing that baseline itself. Hope that makes sense.

**Comment by knubie** [comment]
That makes perfect sense, thanks for the explanation!

**Comment by wellle** [comment]
@knubie: With your config I managed to reproduce and understand the issue. The grey box is basically just the default highlighting of `FoldColumn`. Both of the issues could actually be "fixed" by adding this to your syntax highlighting file:
```vim
hi FoldColumn ctermbg=Black ctermfg=Black
```
But you also have some fold settings, so I assume you might want to keep your non black fold column.

And the blue characters are actually fold markers. You can see them in your buffer too if you `set foldcolumn=5` for example.

I fixed both of these issues in #26 for both Neovim and Vim by:
- Disabling folding in the popup windows (so the blue characters won't show up anymore)
- Using `Normal` highlighting for the `SignColumn`. That way the sign column will use the same background color as the popup window.

All in all it's looks much better than before. I did notice the grey sign column in Vim before but it didn't bother me enough to look into it. I hadn't seen the blue characters yet because I don't have `set foldmethod=indent` in my vimrc.

Thanks again! 🙌

**Comment by wellle** [comment]
@knubie: I had another look through your vimrc, I noticed you have some mappings about last and next text objects. Just wanted to mention that I have another plugin which expands on that idea quite a bit: 
https://github.com/wellle/targets.vim :v:

**Comment by knubie** [comment]
@wellle Awesome! thanks so much for looking into this for me. Love your work.
