### ISSUE TITLE
It'd be nice if we could show the line number of the context

### ISSUE THREAD

**Issue by lourenci** [wellle/context.vim#40]
Thanks for the plugin.

Sometimes, I'm reading a lot of specs and want to jump right to that context. Is there some way to do that? Maybe if we had the line number on the left of the context?

**Comment by wellle** [comment]
Hey, thanks for the issue! I agree that would be great! There's a few caveats though:
1. Setting `'number'` in the context popup doesn't work as it can only show the line numbers within the buffer, so it would be just `1, 2, 3, ...` instead of the corresponding line numbers. And this would also only work well (without breaking the alignment) if you buffer has `'number'` set too.
2. I could prefix the lines with the line number, but that breaks syntax highlighting (at least in most languages). So this would be a pretty big sacrifice.
3. I could append the line numbers to the context lines. I could probably even align them on the right. I actually already have some debugging code I sometimes use which does include the line number. It looks like this:

    <img width="1199" alt="Screenshot 2020-02-03 22 42 22" src="https://user-images.githubusercontent.com/474504/73693479-95e54e00-46d6-11ea-9500-f1b324be93b8.png">

    But that has a problem with syntax highlighting too. My debugging code has hardcoded `//` in it. For production use I'd need a way to use proper comment delimiters in order to not break highlighting (for example it would be `#` in bash etc.)

So for now I'm not sure what the best way would be to go about this. What do you think?

As for navigating to the context lines. If you just want to just to the beginning of the current function try `[[`. There's also `[m`. And if you use this plugin you can jump between the different context levels by typing `[-`: https://github.com/jeetsukumaran/vim-indentwise

**Comment by lourenci** [comment]
Sorry, I'm a layman in vimscript. 😔

In the alternatives above, I think I'd stick with the third option, but you'd have a hard work figuring out what is the right comment symbol for the language. What if you start with a simple naive implementation mapping the most commons languages these days? I would be a simple MPV for the feature.

Anyway, your lib is awesome. Thanks for it.

**Comment by zsugabubus** [comment]
> I could prefix the lines with the line number, but that breaks syntax highlighting (at least in most languages). So this would be a pretty big sacrifice.

Note that you can do something like [this](https://user-images.githubusercontent.com/30056345/80918629-81f0cd00-8d55-11ea-949c-e877a3fb4184.png) and [this](https://user-images.githubusercontent.com/30056345/80918631-82896380-8d55-11ea-9293-2028ae493e34.png) by forgetting about filetype and just “simply” copying highlights and manually constructing a line-looking line.

**Comment by wellle** [comment]
@zsugabubus: That looks very nice! Can you help me with how that could be done?

**Comment by zsugabubus** [comment]
Of course. Just finished with it today, so… _may_ contain bug… but it seems working.

The core of the magic is here:
https://github.com/zsugabubus/vim-paperplane/blob/c902d9f8a83d2a6ab51e9e85e1a6e821d8d161ab/autoload/paperplane.vim#L98-L137

If you have any questions let me know, but I think it can be easily ported with not too much effort.

**Comment by wellle** [comment]
Wow, that's awesome! Thank you so much for sharing this! ❤️ 

Btw, did you manage to improve the performance in your implementation in comparison to context.vim? Or did you find anything else you think could be improved in here? Please feel free to open new issues, I'd be very interested in your feedback 👍

**Comment by zsugabubus** [comment]
> Wow, that's awesome! Thank you so much for sharing this

Wait at least one day until you start digging yourself into it. I just now saw another little bug.

> did you manage to improve the performance

I wouldn’t say so, but I think there is not too much room for improvements since `search()` is itself consumes (at least) 25-30% CPU (~half). Other things are negligible compared to this.

> Please feel free to open new issues, I'd be very interested in your feedback

Okay…

**Comment by wellle** [comment]
@lourenci @zsugabubus @toddyamakawa @christopher-francisco @scarfacedeb @wmusical:
This has been done in #81 🎉 

Huge thanks again to @zsugabubus for helping out with their ideas (and reference implementation!) of how to do highlights manually. I basically took their approach and integrated it to context.vim. I'm very happy with the result. Here's a new screenshot:

![context-example](https://user-images.githubusercontent.com/474504/91095474-bcf87280-e65c-11ea-89f2-d3d208173369.png)
