### ISSUE TITLE
Feature request: Add option to draw "context border char" from the first column

### ISSUE THREAD

**Issue by dominikduda** [wellle/context.vim#43]
This probably should be optional.

I'd love to have the `context_border_char` drawn from the very first column from the left side instead of from one where current indent ends.

This would separate the plugin window better and make it more readable.

Example with setting: `let g:context_border_char = '⬍'`

![Selection_001](https://user-images.githubusercontent.com/14922999/73760500-b0b6d180-476d-11ea-8abb-3a372eace181.png)

**Comment by wellle** [comment]
Hey, I pushed a branch `43-full-border`. Could you check if that works for you?

I does not show the border across the number column though, as we currently use `'foldcolumn'` to add padding for alignment. In order to have the border line go all the way to the left some bigger changes would need to be made.

**Comment by dominikduda** [comment]
Its fine as is, It would not make sense to me to draw it in line column (just in columns with actual editable text).

It works

**Comment by wellle** [comment]
Okay, thanks for the feedback. I'll consider making this available via a setting.

**Comment by wellle** [comment]
@dominikduda: I opened a PR which should take care of this: https://github.com/wellle/context.vim/pull/54

Could you try that branch `44-indent-functions` and put this in your vimrc?
```vim
let g:Context_border_indent = { -> 0 }
```

Thanks!
