### ISSUE TITLE
Empty lines displayed in some files.

### ISSUE THREAD

**Issue by dominikduda** [wellle/context.vim#61]
Steps to reproduce:
- Open vim with not too high window (50 visible lines is OK)
- Open attached sample file
- Press `ctrl+e` 10 times
- Observe that context only displays 1 blank line (screenshot)
![image](https://user-images.githubusercontent.com/14922999/76153685-9440e880-60cf-11ea-8d76-f5f89104ef7f.png)

Sample file:
```js
import React from 'react'
import screenfull from 'screenfull'

import { shallow } from 'enzyme'

import {
  BrowserDetector,
  ListDimensionsUpdater,
  WebRTCWrapper,
  isInConferenceUsingPhone,
  publishVideoStreamMessage,
} from '../../../app/services'
import {
  ChatCallsChannelHandler,
  WebRTCHelpers,
  WebRTCDevices,
  changedCalls,
} from '../../../app/Conference/services'





































































```

**Comment by dominikduda** [comment]
Also in the same file when ctrl+e is pressed 11 times, the context show with no line at all:
![image](https://user-images.githubusercontent.com/14922999/76153695-b9355b80-60cf-11ea-822c-b8248888be4f.png)

**Comment by wellle** [comment]
@dominikduda: Thanks for the report. This is expected behavior though. In your first case (after `10<C-E>`) the topmost lines in the buffer are 
```
  publishVideoStreamMessage,
} from '../../../app/services'
```
The context of each of those lines is
```
import {
```
But together with the border line `▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ <context.vim>` it would need two lines to display, so there is not enough space to do so. So what context.vim does instead in that case is basically to hide those lines. The reasoning is that this plugin always wants to make sure that all visible lines have their full context shown. And this seems to be the only way to do that.

Does that make sense?

**Comment by wellle** [comment]
@dominikduda: Did you see my comment above? Are you happy with that explanation or do you have any suggestions on this topic? Thanks!

**Comment by maxigit** [comment]
I have also this problem a lots and I understand what you mean. However, I think a simple fix would be to display the context window at the bottom ( as you do when there is not enough space).

**Comment by wellle** [comment]
Just for the record, we don't ever display the context at the bottom anymore. And I'd prefer to not bring that back. 

Please let me know if those blank lines are a big issue for you. In that case I can probably create a branch without them and have you try that. :v:

**Comment by wellle** [comment]
Btw, I changed this in #76, there should be no more blank lines in the context :v:

**Comment by maxigit** [comment]
It seems to work indeed but I found the behavior a bit confusing. At first I thought this plugin stopped working because it didn't show any context (my cursor was on a function which started in the visual area). I understand that is the intended behavior but I'm not sure I'm liking it.
So the first question is, is there a way to disable it and go back to original behavior ? (I toggle would probably best).
One great use of this plugin it to know in which branches you are when there is lots of nested if for example.
I thought the use case for displaying the context on the cursor what that, but it doesn't really work.
So I was thinking would it be possible to show the context corresponding to the cursor line in full regardless if those lines are visible or not.

For example

    function a
       if a
          ...
          if b
           >>>> the cursor is there<<<

will display in the context `function a` `if a` and `if b` regardless what is visible so you might end up with

     function a
       if a
           if b
     ------------ end of context
     a function
       ....
    function a
       if a
          ...
          if b
           >>>> the cursor is there<<<
    
     It might seem weird explain like that, but I think when you move the cursor it will actually makes sense.

**Comment by wellle** [comment]
@maxigit: Thanks for the feedback! Could you open a separate issue about this suggestion? Thank you!

Also FYI there has been some discussion about the filtered vs non-filtered approach in #10. I was hesitant about this general change at first too, but now I actually quite like it. Maybe you can try the new way for a few days and see if it starts to make sense to you. If not please open a new issue :v:
