### ISSUE TITLE
[Bug] Plugin breaks vertical cursor movements even when disabled

### ISSUE THREAD

**Issue by Ironimus** [wellle/context.vim#84]
Here's a screen recording of the issue:
![Screen-Recording-2020-08-27-at-1 (1)](https://user-images.githubusercontent.com/8076719/91415783-322f9780-e857-11ea-9550-ac2b1b5693e6.gif)

Compare to how it works without the plugin:
![Screen-Recording-2020-08-27-at-1](https://user-images.githubusercontent.com/8076719/91415905-525f5680-e857-11ea-9592-b6de239d59dd.gif)

`:ContextDisable` doesn't fix it

Broken in both vim and neovim

**Comment by wellle** [comment]
Thank you, I can reproduce this behavior, will look into it 👍

**Comment by wellle** [comment]
@Ironimus @yutakatay: Turns out that setting `'virtualedit'` temporarily resets the cursor position's `curswant` property (which column the cursor would like to be on) to the column it's actually on. So the fix #87 was to save and restore the cursor position (even though the cursor itself didn't actually move) in order to retain the `curswant` property. Please try again, and thanks again for reporting 👍

**Comment by yutakatay** [comment]
I've just tried it. It seems to be fixed properly.
Thank you :smile:
